### ISSUE TITLE
1.0: SuperGiant + DigitalOcean + Kubernetes + LoadBalancing

### ISSUE THREAD

**Issue by bartoszhernas** [supergiant/supergiant#174]
Hi,

I am trying to set up kubernetes cluster using SuperGiant and I love it already!

I see that documentation (besides tutorials) is missing. I was able to instal CLI and figure out how to apply kubernetes configuration.

### I have one problem with load balancing though:
I have set up nginx-ingress-controller, specified it's service and hardcoded two IP addresses from minions. Then supergiant removed my node and created new one, so IP is not valid anymore.

What is the correct way to set up proper load balancing?

### Private networks

On DigitalOcean to not pay for internal traffic you usually set up private network and use different IPs to communicate in the datacenter. Is this supported by SuperGiant?

**Comment by gopherstein** [comment]
I am in the process of updating the Supergiant DO provider. It should use internal IPs after the update. I also hope to automate a loadbalaning scheme too.. Typically you would specify an "endpoint" in supergiant to provide a static IP loadbalancer. I will probably use Kube-Proxy to do this in digital ocean as DO has no built in load balancing service. I will leave this issue open and close it when I release the updated provider. As a work around, You can manually create a "Load Balance" droplet. This would be a CoreOS droplet, with the Kube-proxy installed. Requests would hit this kube-proxy, then be routed to the proper kubernetes node. (the kube proxy will keep track of changing node IPs for you. Here is a link to an example tube-proxy configuration on CoreOS. https://github.com/supergiant/supergiant/blob/master/config/providers/openstack/minion.yaml#L43

You essentially could use this whole yaml to build your proxy. However... You will want to mark the kubelet "https://github.com/supergiant/supergiant/blob/master/config/providers/openstack/minion.yaml#L174" to not register (false) so that the Supergiant API does NOT try to manage it.

**Comment by lohmander** [comment]
@gopherstein Any ETA on the updated DO provider? I'm also looking for a solid solution to externally access kubernetes services on Digital Ocean (with Supergiant).

**Comment by gopherstein** [comment]
@lohmander I am building in a tube-proxy node to act as the load-balancer for Digital Ocean. There is one limitation to this model... I don't think a user will be able to offer 2 or more services on the same port. I might be able to find some way to get around this... not sure... You think this would be something that would cause a big hangup for you?

**Comment by maikelvl** [comment]
This has just been announced: https://www.digitalocean.com/products/load-balancer/
https://digitalocean.uservoice.com/forums/136585-digitalocean/suggestions/2670745-load-balancer-load-balancing-service

**Comment by lohmander** [comment]
@gopherstein Since I haven't used SG on AWS I'm not sure how you setup the load balancers there, but would it work to have an ingress controller routing all traffic to the appropriate service behind the load balancer?

I initially thought of a solution where there was some configuration option to assign a static ip  to a node (maybe use floating ips so that it still can be replaced?), and then have an ingress controller live on that node.

Either way, as maikelvl pointed out, it'd probably be better to just integrate with DO's own load balancer service once its ready.

**Comment by gopherstein** [comment]
@maikelvl @lohmander I will play with both today and let you know what I find.

**Comment by gopherstein** [comment]
:-( Coming Soon... Well, I guess not today....

**Comment by lohmander** [comment]
@gopherstein Maybe DO could provide some early access, since it should be in their interest to actually have some quick initial Kubernetes setup for their platform that's actually production ready. 🍾 

Overall love what you're doing with Supergiant and the fact that you decided to provide DO support so early. Would love to see all the quirks be worked out so that it'd be a viable solution for our production use. Which in our case, is mostly an issue of reliable external access.

**Comment by tvarsis** [comment]
Any news on this?

**Comment by gopherstein** [comment]
hmm... looks like they should be available via API. Yeah, I will get this going.

**Comment by abedinpour** [comment]
Hi,
Any updates on this?

**Comment by TheKLARKEN** [comment]
Hi, @abedinpour! 😄 Currently, we're crunching through a lot of changes and improvements to our codebase as we push towards a 1.0.0 release! 🎊 Our goal is to have load balancing be a dedicated, custom process to make it easier for users to abstract from their cloud providers.

We've on-boarded a very talented team recently, but we don't want to make promises too early. With our current velocity, we should be able to have news for you about its place on the roadmap in the coming weeks! 👍

**Comment by TheKLARKEN** [comment]
Hi, @abedinpour, thanks for waiting so long for an update. 🙂 1.1.0 has just been released (👍), but doesn't contain dedicated loadbalancing. On the other hand, Supergiant 2.0 is in the works, and has big changes planned, including this one. I still can't give a solid date, but this time I know it's a real, planned change on our roadmap as of our last planning session.

I'll update you again when we have a release window!

**Comment by TheKLARKEN** [comment]
Hey, everyone! The team no longer has this on the roadmap, because of Supergiant 2.0 taking priority. I'll update if I find out that we'll be working on it, because I know that it's a goal we want to reach, but there's currently no ETA for us to begin work on it.

**Comment by gopherstein** [comment]
Consolidating this issue here https://github.com/supergiant/supergiant/issues/447 as SG should have a way of creating universal LBs for all providers.
