### ISSUE TITLE
.sh deployment scripts 

### ISSUE THREAD

**Issue by ChrisCates** [supergiant/supergiant#184]
We should add deployment scripts for the for the supergiant dashboard.

We can have a select box on the site displaying your OS version and desired script and you can download a cURL script accordingly.

**Comment by FestivalBobcats** [comment]
Bringing this to the attention of @briansage. Since this is technically related to supergiant-cms (a private repository), I'll close this here and we can discuss in a Slack channel.

But, it should be as simple as making some JavaScript, triggered by OS select box, to fetch the latest release for the correct OS from the Github releases page.
