### ISSUE TITLE
2.0: Suggestion: Add banner telling people this product is not ready

### ISSUE THREAD

**Issue by zwhitchcox** [supergiant/supergiant#596]
Please put a banner on the README.md, so people don't try to use this product before it is ready. It will only frustrate your users, and make them not come back in the future. I would like to use this product in the future, but I need to know when it will be ready.

**Comment by TheKLARKEN** [comment]
Hi, @zwhitchcox! I was recently given half of each work day to take on the duty of handling our docs, so I'll be updating everything incrementally (dealing with these invalid tutorials, too). We didn't have anyone or any solid process before, so that's why things are... messy--and there are still vast issues to fix. 🙂 

I agree that users should know what is and isn't ready, and that docs should be at a minimum clear and complete before release, which is why I've been put in charge of it.

If you check our official docs, you'll see that there's already a banner explaining that installation is currently broken and under review. 🙂

**Comment by zwhitchcox** [comment]
Ok, that is another question I had, I can not seem to find the official docs.

https://github.com/supergiant/supergiant/tree/master/docs (top google result broken link)
https://readthedocs.org/projects/supergiant/ (2nd google result broken link)
https://github.com/supergiant/supergiant-api-docs (??)
https://supergiant.io/tutorials (already mentioned)
https://supergiant.readme.io/v2.0.0/ (link from README, but not much info)

So, it's a little confusing for me to know which one to go to, that's another thing that would be nice as a user to just have one and only one source of docs, so I only have one place to look.

So, I feel like I'm being really negative, but just want to stress, that's out of a strong desire to use the amazing product that is the end goal!

**Comment by TheKLARKEN** [comment]
Thank you for your input, I'll figure out some way to get the access to docs to be more intuitive, and maybe I can get the search engine crawlers to cooperate! We just put our new docs site, supergiant.readme.io online, today, so that may improve on its own. 🙂

**Comment by MrDienns** [comment]
> Ok, that is another question I had, I can not seem to find the official docs.
> 
> https://github.com/supergiant/supergiant/tree/master/docs (top google result broken link)
> https://readthedocs.org/projects/supergiant/ (2nd google result broken link)
> https://github.com/supergiant/supergiant-api-docs (??)
> https://supergiant.io/tutorials (already mentioned)
> https://supergiant.readme.io/v2.0.0/ (link from README, but not much info)
> 
> So, it's a little confusing for me to know which one to go to, that's another thing that would be nice as a user to just have one and only one source of docs, so I only have one place to look.
> 
> So, I feel like I'm being really negative, but just want to stress, that's out of a strong desire to use the amazing product that is the end goal!

In addition, the Swagger spec (API documentation) was last updated for version 0.8 or something. We are looking at 1.1.0 right now. The fact that this spec is outdated makes the API unusable. I know that the project team is working on a 2.0 release, but right now, the current version isn't even properly usable for most users due to missing critical end user documentation. Having this new Swagger spec out should be top priority, and manually making one shouldn't be more than a day work.

**Comment by gopherstein** [comment]
@TheKLARKEN Can you add a mention in the README for SG being considered BETA?
